import { Button, VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";


import { useWeb3Auth } from "../services/web3auth";
import { WALLET_ADAPTERS } from "@web3auth/base";
import { useEffect, useState } from "react";
import { useAuthContext } from "../providers/auth";
import { getRedirectUrl } from "../services/utils";

const Home: NextPage = () => {
  const {
    user,
    provider,
    login,
    logout,
    getPrivateKey,
    isLoading,
  } = useWeb3Auth();

  const { getCurrentSession } = useAuthContext();
  const [link, setlink] = useState("")

  const handleSignOut = async () => {
    await logout();
  };

  const handleSignIn = async () => {
    // refresh token
    const session = await getCurrentSession(true);
    if (!session) return;

    const id_token = session.getIdToken().getJwtToken();
    console.log("id_token",id_token);

    await login(WALLET_ADAPTERS.OPENLOGIN, "jwt", {
      id_token,
    });
  };

  const handleGetPrivateKey = async () => {
    await handleSignIn();
    return await getPrivateKey();
  };

  const redirectUnrealWebServer = async () =>{
    const redirectUrl = getRedirectUrl();
    const privKey = await handleGetPrivateKey()
    const authToken = (await getCurrentSession())?.getIdToken().getJwtToken()
    const result = {
      privKey,
      authToken,
    }
    const resultEncode = Buffer.from(JSON.stringify(result), "utf-8").toString('base64');
    
    if(result.privKey){
      setlink(`${redirectUrl}`)
      window.location.replace(`${redirectUrl}#${resultEncode}`);
    }
  }

  useEffect(() => {
    (async () => {
      if(!isLoading ){     
        redirectUnrealWebServer()
      }
    })();
  }, [isLoading,provider])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack justify="center" h="100vh">
        {isLoading ? (
          "Loading..."
        ) : user ? (
          <>
            {/* <Button onClick={handleSignOut}>SIGN OUT</Button>             */}
          <h2>wellcome test login atherlabs x web3auth</h2>
          <p>{link}</p>
          </>
        ) :""}
    
      </VStack>
    </div>
  );
};

export default Home;
