import { Button, VStack } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";
import { sign } from 'jsonwebtoken'


import { useWeb3Auth } from "../services/web3auth";
import { WALLET_ADAPTERS } from "@web3auth/base";
import { useEffect, useState } from "react";
import useQuery from "../services/useQuery";

const Home: NextPage = () => {
  const query = useQuery()
  const {
    user,
    provider,
    login,
    logout,
    getPrivateKey,
    web3Auth,
    chain,
    isLoading,
  } = useWeb3Auth();



  const handleSignOut = async () => {
    await logout();
  };

  const handleGetPrivateKey = async (id_token:string) => {
    await login(WALLET_ADAPTERS.OPENLOGIN, "jwt", {
      id_token,
    });
    return await getPrivateKey();
  };

  useEffect(() => {
    (async () => {
      
      const base64 = window.location.href.split("#")[1];
      
      if(!isLoading && provider && base64){
        const dataBase64 = JSON.parse(Buffer.from(base64, 'base64').toString('binary'));
        const redirectUrl = dataBase64.init.redirectUrl;
        console.log(dataBase64);
        
        console.log("redirectUrl",redirectUrl);
        const id_token = dataBase64.init.id_token;
        // const sk = await handleGetPrivateKey(id_token)
        
        // const jwt = sign({
        //   privateKey:sk
        // }, 'secret', { expiresIn: 60 * 60 });
        // console.log(jwt);
        // if(sk)
        //   window.location.replace(`http://localhost:12345/success=${jwt}`);
      }
    })();
  }, [query?.id_token,isLoading,provider])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack justify="center" h="100vh">
        {isLoading ? (
          "Loading..."
        ) : user ? (
          <>
            <Button onClick={handleSignOut}>SIGN OUT</Button>            
          </>
        ) :""}
    
      </VStack>
    </div>
  );
};

export default Home;
