
import type { NextPage } from "next";
import Head from "next/head";

import styles from "../styles/Home.module.css";

import { useWeb3Auth } from "../services/web3auth";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const {
    provider,
    logout,
    isLoading,
  } = useWeb3Auth();

  useEffect(() => {
    (async () => {
      await logout();
    })();
  }, [isLoading,provider,logout])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
