import { VStack } from "@chakra-ui/react";
import { AtherIdWidget, AtherIdWidgetProvider } from "@sipher.dev/ather-id";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <VStack justify="center" h="100vh">
        <AtherIdWidget width={400} margin="auto" p="24px" />
      </VStack>
    </div>
  );
};

export default Home;
